const uint8_t GPIOPIN[4] = {D4, D5, D6, D7}; // Led
float   tempValue,  pretempValue;
float   humiValue,  prehumiValue;
float   co2Value,   preco2Value;
String  ledGpio[4]  = {"OFF", "OFF", "OFF", "OFF"};
int     cnt         = 0;

String getPage() {
    String page = "<html lang='en'>";
    page += "<head>";
    page +=     "<meta charset='UTF-8' http-equiv='refresh' content='15'>";
    page +=     "<name='viewport' content='width=device-width, initial-scale=1'>";
    page +=         "<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css'>";
    page +=         "<script src='https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js'></script>";
    page +=         "<script src='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js'></script>";
    page +=         "<title>ESP8266 Demo</title>";
    page += "</head>";
    page += "<body>";   
    page +=     "<div class='container-fluid'>";     
    page +=         "<div class='row'>";
    page +=             "<div class='col-md-12'>";
    page +=                 "<h1>ESP8266 웹서버 데모</h1>";
    page +=                 "<h3 id='nowtime' style='color:gray'></h3>";
    page +=                     "<script>";
    page +=                         "var now = new Date();";
    page +=                         "var nowtime = now.getFullYear() + '년 ' +";
    page +=                             "(now.getMonth() + 1) + '월 ' +   now.getDate() + '일 ' +";
    page +=                             "now.getHours() + '시 ' + now.getMinutes() +";
    page +=                             "'분 ' + now.getSeconds();";
    page +=                         "document.getElementById('nowtime').innerHTML = nowtime;";
    page +=                     "</script>";    
    page +=                 "<h3>Sensing & Control Mini station </h3>";
    page +=                 "<ul class='nav nav-pills'>";
    page +=                     "<li class='active'>";
    page +=                         "<a href='#'> <span class='badge pull-right'>"; 
    page +=                         tempValue; 
    page +=                         " &deg;C</span>온도</a>";
    page +=                     "</li>";
    page +=                     "<li class='active'>";
    page +=                         "<a href='#'> <span class='badge pull-right'>"; 
    page +=                         humiValue; 
    page +=                         " %</span>습도</a>";
    page +=                     "</li>";
    page +=                     "<li class='active'>";
    page +=                         "<a href='#'> <span class='badge pull-right'>"; 
    page +=                         co2Value;
    page +=                         " ppm</span>CO2</a>";
    page +=                     "</li>";
    page +=                 "</ul>";
    page +=                 "<table class='table'>";
    page +=                     "<thead>";
    page +=                         "<tr>";
    page +=                             "<th>센서</th>";
    page +=                             "<th>측정</th>";  
    page +=                             "<th>현재 값</th>"; 
    page +=                             "<th>이전 값</th>";  
    page +=                         "<tr>";
    page +=                     "</thead> ";
    page +=                     "<tbody>";
    page +=                         "<tr>";
    page +=                             "<td>BME280</td>";
    page +=                             "<td>온도</td>";
    page +=                             "<td>"; 
    page +=                                 tempValue; 
    page +=                                 " &deg;C</td>";
    page +=                             "<td>";
    page +=                                 pretempValue; 
    page +=                                 " &deg;C</td>";
    page +=                         "</tr>";
    page +=                         "<tr class='active'>";
    page +=                             "<td>BME280</td>";
    page +=                             "<td>습도</td>"; 
    page +=                             "<td>"; 
    page +=                                 humiValue; 
    page +=                                 " %</td>";
    page +=                             "<td>"; 
    page +=                                 prehumiValue; 
    page +=                                 " %</td>";
    page +=                         "</tr>";
    page +=                         "<tr>";
    page +=                             "<td>MH-Z16</td>";
    page +=                             "<td>CO2</td>";
    page +=                             "<td>"; 
    page +=                                 co2Value; 
    page +=                                 " ppm</td>";
    page +=                             "<td>"; 
    page +=                                 preco2Value; 
    page +=                                 " ppm</td>";
    page +=                         "</tr>";
    page +=                     "</tbody>";
    page +=                 "</table>";
    page +=                 "<h3>GPIO</h3>";
    page +=                 "<table>";
    page +=                     "<tr>"; 
    page +=                         "<td style='width:200px'><h4 class='text-left'>D4 <span class='badge'>"; 
    page +=                             ledGpio[0]; 
    page +=                             "</span></h4></td>"; 
    page +=                         "<td style='width:200px'><form action='/' method='POST'><button type='button submit' name='D4' value='1'";
    page +=                             "class='btn btn-success btn-lg'>ON</button></form></td>";                 
    page +=                         "<td style='width:200px'><form action='/' method='POST'><button type='button submit' name='D4' value='0'";
    page +=                             "class='btn btn-danger btn-lg'>OFF</button></form></td>";  
    page +=                     "</tr>"; 
    page +=                     "<tr>";
    page +=                         "<td style='width:200px'><h4 class='text-left'>D5 <span class='badge'>";
    page +=                             ledGpio[1]; 
    page +=                             "</span></h4></td>";          
    page +=                         "<td style='width:200px'><form action='/' method='POST'><button type='button submit' name='D5' value='1'";
    page +=                         "class='btn btn-success btn-lg'>ON</button></form></td>"; 
    page +=                         "<td style='width:200px'><form action='/' method='POST'><button type='button submit' name='D5' value='0'";
    page +=                         "class='btn btn-danger btn-lg'>OFF</button></td>"; 
    page +=                     "</tr>";
    page +=                     "<tr>";
    page +=                         "<td style='width:200px'><h4 class='text-left'>D6 <span class='badge'>"; 
    page +=                             ledGpio[2]; 
    page +=                             "</span></h4></td>";
    page +=                         "<td style='width:200px'><form action='/' method='POST'><button type='button submit' name='D6' value='1'";
    page +=                             "class='btn btn-success btn-lg'>ON</button></form></td>";
    page +=                         "<td style='width:200px'><form action='/' method='POST'><button type='button submit' name='D6' value='0'";
    page +=                             "class='btn btn-danger btn-lg'>OFF</button></form></td>";
    page +=                     "</tr>";
    page +=                     "<tr>";
    page +=                         "<td style='width:200px'><h4 class='text-left'>D7 <span class='badge'>"; 
    page +=                             ledGpio[3]; 
    page +=                             "</span></h4></td>";
    page +=                         "<td style='width:200px'><form action='/' method='POST'><button type='button submit' name='D7' value='1'";
    page +=                             "class='btn btn-success btn-lg'>ON</button></form></td>"; 
    page +=                         "<td style='width:200px'><form action='/' method='POST'><button type='button submit' name='D7' value='0'";
    page +=                             "class='btn btn-danger btn-lg'>OFF</button></form></td>"; 
    page +=                     "</tr>";
    page +=                 "</table>";
    page +=                 "<p><a href='https://github.com/dcback/ESP8266/blob/master/Example/WebServer/esp8266_Server4.ino'target='_blank'>GithubLink</p>";
    page +=             "</div>";
    page +=         "</div>";
    page +=        "</div>";
    page +=     "</body>";
    page += "</html>";
    return page;
}
